feat: add cameraMode options for tracking location changes
ramani-maps/ramani-maps pull request #93
Opened 2024-11-02 15:51 UTC by torrybr

Allow users to set the `CameraMode` for tracking location changes. CameraMode options and sdk information can be found [here](https://docs.mapbox.com/android/legacy/maps/guides/location-component/#cameramode).

Closes https://github.com/ramani-maps/ramani-maps/issues/72

2024-11-02 16:55 UTC, torrybr commented
Whats the best approach for listening to `CameraTrackingChanges`?  Something such as:

```
    this.locationComponent.addOnCameraTrackingChangedListener(object : OnCameraTrackingChangedListener {
        override fun onCameraTrackingDismissed() {
            // Optionally handle if the tracking is dismissed
        }

        override fun onCameraTrackingChanged(currentMode: Int) {
            // When the camera mode changes, ensure it is set to the desired mode
            if (currentMode != cameraMode) {
                locationComponent.cameraMode = cameraMode
            }
        }
    })
```

2024-11-13 11:28 UTC, JonasVautherin requested changes
Not sure why I took so long to review that, sorry (I had a couple busy weeks).

Would you mind rebasing on `main` (and I took this opportunity to add two nitpicks :innocent:) and then we can merge it?

Thanks a lot! :rocket:

2024-11-13 11:28 UTC, JonasVautherin commented on ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
> +                cameraMode
Nitpick :innocent: 

```suggestion
                cameraMode,
```

2024-11-13 11:28 UTC, JonasVautherin commented on ramani-maplibre/src/main/java/org/ramani/compose/MapLibre.kt
> +    cameraMode: Int
Nitpick again :see_no_evil: 
```suggestion
    cameraMode: Int,
```

2024-11-14 03:48 UTC, torrybr commented
Rebased and comments addressed 👍  Before we merge it, Im wondering If I need the `addOnCameraTrackingChangedListener` as in the linked examples because simply adding  `this.locationComponent.cameraMode = cameraMode` is not triggering the cameraMode change. Would you mind taking a quick look to confirm? Thanks for all your help!

2024-11-14 10:58 UTC, JonasVautherin commented
> this.locationComponent.cameraMode = cameraMode is not triggering the cameraMode change

Oh, so it's not working then?

Which examples are you referring to? Is there a small application that I could quickly run to see what's happening?

2024-11-15 01:22 UTC, torrybr commented
I updated the [`Location` example](examples/location/app/src/main/java/org/ramani/example/location/MainActivity.kt) so that it uses a tracking camera mode. You should be able to set a gps route through android studio to test! Thanks!

2024-11-25 12:29 UTC, JonasVautherin commented
I haven't had time to try it yet, but it's still planned! In the meantime, did you manage to make it work?

2024-11-25 19:42 UTC, torrybr commented
I updated with a `addOnCameraTrackingChangedListener` which seems to work properly and rotate the map as expect when loading the `Location` example i mentioned above. Im curious to see what you think! Im not quite sure why it requires this listener to function as expected

2024-11-25 21:09 UTC, JonasVautherin commented
Amazing, I'll test that ASAP!

2024-11-27 14:37 UTC, torrybr commented
Thanks for taking a look!

2024-11-30 21:57 UTC, JonasVautherin approved these changes
Just tested it and it works! Thanks a lot! :rocket:

2024-11-30 21:58 UTC, merged